### PR TITLE
refactor(permissions): extract RBAC matrix + resolver to @shelf/permissions

### PR DESCRIPTION
**Pull request by carlosvirreira**
## Need

PR #2753's review surfaced that the companion carried a hand-copied mirror of the webapp's permission matrix, and that the webapp's effective authorization was itself split across **three** places, not two:

1. `Role2PermissionMap` — the data.
2. An ADMIN/OWNER allow-all short-circuit living only inside the server's `hasPermission()`.
3. A **second, independent** copy of both the matrix walk and that short-circuit inside `permission.validator.client.ts`, which gates ~47 UI call sites.

Two apps, three fragments, zero drift protection. A change to the short-circuit in any one of them would not have reached the other two.

## What changed

- **New `packages/permissions` (`@shelf/permissions`)** — the vocabulary, the role matrix, and `roleHasPermission()`: the pure resolver *including* the ADMIN/OWNER short-circuit. No Prisma, no Node APIs — Metro-bundleable by design. Split into `roles` / `vocabulary` / `matrix` / `resolver`, with `index.ts` as re-exports only.
- **Server validator** delegates the decision to the shared resolver; keeps the `UserOrganization` lookup + `ShelfError` semantics.
- **Client validator** is now a thin adapter over the same resolver — its hand-rolled matrix walk and private short-circuit are gone. `roleHasPermission` gained action-**array** (any-match) support to make that possible, which is the capability that had kept it hand-rolled. Public signature unchanged, so all 47 call sites are untouched. It also drops its `@prisma/client` **value** import, so a Prisma value leaves the client bundle.
- **Companion `lib/permissions.ts`** — the hand-copied matrix is **deleted**; `userHasPermission` is a thin adapter over the same resolver.
- **Prisma role parity guard** moved to its own `permission.roles-parity.ts`, which documents *why* the role union is re-declared rather than imported: `@prisma/client` is a value import that pulls a ~19 MB native query engine binary, which Metro cannot bundle. A runtime test covers the same invariant and fails **naming the drifted role**, rather than the compile-time guard's `Type 'true' is not assignable to type 'never'`.

After this, every RBAC decision in both apps resolves through one function.

## Verification

Checked mechanically, not by eye:

- `Role2PermissionMap` is **byte-identical** to main's after normalising only the role-key syntax (`[OrganizationRoles.BASE]:` → `BASE:`) — 399 lines vs 399, zero diff. Both enums identical too. Re-verified after the module split.
- A brute-force over all 1,800 `(role, entity, action)` triples against main's matrix produced **0 mismatches**.
- The parity guard was compile-tested in both directions — it errors when Prisma gains a role *and* when the package gains one.
- The companion adapter was proven behaviourally identical to the deleted mirror for every triple its call sites use. (The old mirror had no short-circuit; it hand-encoded the effective result, e.g. listing `qr: ["read","update"]` for ADMIN/OWNER. The new short-circuit reproduces that exactly.)

**Tests: 27.** 14 in the package (`node:test`, matching `@shelf/quantity-control`) covering the rule itself — array any-match, empty-array denial, the short-circuit beating an all-denied array, unknown role strings, and both halves of the unknown-entity behaviour. 13 in the webapp covering what is genuinely the apps' own: the server's DB lookup and `ShelfError` semantics, the role parity invariant, and a 1,800-combination sweep asserting the client adapter never disagrees with the resolver — so a hand-rolled branch creeping back in fails the suite instead of silently re-forking the UI from the server.

**CI now runs package tests at all.** A new step runs `pnpm -r --filter "./packages/*" run test`. Previously CI only ran the webapp's vitest, so `@shelf/quantity-control`'s and `@shelf/database`'s suites had **never executed once** — 61 tests, now running. (Deliberately not `turbo run test`: `turbo.json` marks that task `persistent`, since the webapp's `test` script is vitest in watch mode, so it would hang the job.)

**Green:** `tsc -b --force` exit 0 / 0 errors; eslint 0 errors; 4,528 webapp tests; 108 package tests; companion `tsc --noEmit` clean; `pnpm install --frozen-lockfile` exit 0.

**Metro proof:** `expo export --platform ios` produces a full Hermes bundle with the workspace package inlined — the RN-consumption risk is tested, not assumed.

## ⚠️ Requires `pnpm install`

This adds a `packages/*` workspace dependency. Workspace packages are consumed through `node_modules` symlinks that only `pnpm install` creates, so **every existing checkout and every git worktree must re-run `pnpm install` from the monorepo root** or the dev server fails with `Failed to resolve import "@shelf/permissions"`. `vite.config.ts` on main now hard-throws with a "run pnpm install" message rather than letting those errors scroll by. See `.claude/rules/run-pnpm-install-when-workspace-packages-change.md`.

## Known residual: `permission.data.ts` still exists

The shim was going to be deleted, with its ~270 import sites rewritten to `@shelf/permissions` so provenance is visible at every call site. That rewrite typechecks in isolation but tips the webapp program over TypeScript's type-instantiation ceiling:

```
error TS2321: Excessive stack depth comparing types 'UserDefaultArgs<DefaultArgs>'
and 'UserDefaultArgs<InternalArgs & { … 58 more … }>'
```

The depth comes from `@shelf/database` `$extends`-ing the Prisma client across every model; those arg types already sit close to the limit and the extra direct edges push them past it. The error is **not** in permissions code — it lands on whichever Prisma query is deepest when the budget runs out (it moved between the organization and asset service files as call sites were patched), so patching call sites is unbounded rather than a fix.

Bisected to confirm: the package split, the client-validator migration and the parity guard are each green independently; only the import rewrite trips it. The reason is recorded in the shim's own docblock so it doesn't read as an oversight. Deleting it stays the right end state, gated on `@shelf/database` exporting a shallower client type — a change with far wider blast radius than this PR.

## Notes for review

- **Base is `main`.** This was originally stacked on #2753, which has since merged.
- **The QR follow-ups were split out.** This branch previously carried 13 files of unrelated QR / rate-limit behaviour changes (follow-ups to the already-merged #2753). They change a mobile API wire contract, two shared web service error statuses and the companion's claim timing, and the companion half rides the native release train — a deploy-order constraint this package does not have. They now live on `fix/qr-relink-followups`, branched from `main` so it ships independently. **This PR's diff is the extraction only.**
- One deliberate behaviour refinement: an entity/action missing from a role's matrix entry now safe-denies (`false` → 403) instead of throwing a `TypeError` that surfaced as a wrapped 500. Unreachable today — every `entity:` argument is an enum member and there are no casts — but it fails closed either way. The ADMIN/OWNER short-circuit still runs first, exactly as `main` does; both halves are pinned by tests.

### CODE REVIEW

File: apps/companion/app/(tabs)/assets/link-qr.tsx [hunk 1]
```diff
@@ -103,6 +99,26 @@ function LinkQrContent() {
...
+    if (currentOrg.id !== originOrgIdRef.current) {
+      Alert.alert(
+        "Workspace Changed",
+        "The scanned QR code belongs to the workspace you started in. Scan it again from this workspace to link it here.",
+        [{ text: "OK", onPress: () => router.back() }],
+        { cancelable: false }
+      );
+    }
+  }, [currentOrg?.id, router]);
+
```
[the remark this answers is not in the document]
Comment (carlosvirreira) [reply apps/companion/app/(tabs)/assets/link-qr.tsx]: Fixed in 372cfb461: the guard now captures the origin org id on its first availability inside the effect (one-shot useRef initializer could pin undefined during context hydration and never arm). Alert + back-nav still only fire when a later org id differs from the captured origin.

File: apps/webapp/app/routes/api+/mobile+/qr.link-asset.test.ts [hunk 2]
```diff
@@ -123,92 +104,79 @@ describe("POST /api/mobile/qr/link-asset", () => {
...
       assetId: "asset-1",
     });
 
-    expect(status).toBe(403);
-    expect(body.error?.message).toBe(
-      "This QR code is already linked to an asset or a kit."
-    );
-    expect(updateAssetQrCode).not.toHaveBeenCalled();
+    expect(body.error?.message).toContain("already linked to another asset");
   });
```
[the remark this answers is not in the document]
Comment (carlosvirreira) [reply apps/webapp/app/routes/api+/mobile+/qr.link-asset.test.ts]: Fixed in 372cfb461: added status: 403 to the already-linked throws in relinkAssetQrCode (both branches) and relinkKitQrCode (both branches) — they previously fell back to 500. The route test now asserts the 403, and both service tests pin { status: 403, title } on the guard rejection.

File: apps/webapp/test/routes-tests/api+/mobile+/qr.link-asset.test.ts [hunk 3]
```diff
@@ -97,18 +85,11 @@ beforeEach(() => {
...
 describe("POST /api/mobile/qr/link-asset", () => {
-  it("links a claimed-but-unlinked QR to an org asset and returns the qr summary", async () => {
-    mockQr({
-      id: "qr-1",
-      organizationId: "org-1",
-      assetId: null,
-      kitId: null,
-    });
-
+  it("delegates to relinkAssetQrCode with the caller's resolved org and returns the qr summary", async () => {
```
[the remark this answers is not in the document]
Comment (DonKoko) [reply apps/webapp/test/routes-tests/api+/mobile+/qr.link-asset.test.ts]: Not applying this — the premise doesn't hold on this branch. `apps/webapp/app/routes/api+/mobile+/qr.link-asset.ts` imports no rate limiter and its write is `updateAssetQrCode`, not `relinkAssetQrCode`; `apps/webapp/app/utils/rate-limit.server.ts:13` declares `type Bucket = "read" | "bulk"`, so the `"write"` bucket you're quoting doesn't exist here and a 429 test wouldn't compile, let alone pass.

That's because the QR / rate-limit changes were **split out of this PR** onto `fix/qr-relink-followups` (see `57a2bec30`) so the permissions extraction ships on its own — which is also why GitHub has this comment marked outdated. The advice itself is sound against that branch, and the 429 coverage will be picked up there along with the service-level guard tests.

File: packages/permissions/src/index.ts [hunk 4]
```diff
@@ -0,0 +1,569 @@
...
+
+  // Owner and admin can do anything (mirrors the webapp's historical
+  // hasPermission short-circuit — part of effective behavior, not the map).
+  if (roles.includes("ADMIN") || roles.includes("OWNER")) return true;
+
+  // why: `typeof === "string"` (not Array.isArray) discriminates the single
+  // action from the array — PermissionAction is a STRING enum, so its members
+  // are strings at runtime, and this narrows the readonly array cleanly.
+  const actionsToCheck: readonly string[] =
+    typeof action === "string" ? [action] : action;
```
[the remark this answers is not in the document]
Comment (DonKoko) [reply packages/permissions/src/index.ts]: Not applying the code change — the ordering you've flagged is what `main` already does, not something this PR introduces. Both pre-extraction implementations short-circuit ADMIN/OWNER *before* touching the matrix: `apps/webapp/app/utils/permissions/permission.validator.server.ts` (`hasPermission`) and `permission.validator.client.ts` (`userHasPermission`). The extraction preserves that, and where it does differ it differs in the safe direction — a non-privileged role with an unknown entity now returns `false`, where main dereferenced `undefined.includes(...)` and threw a wrapped 500.

The safe-deny contract is scoped to the matrix-lookup path, not the privileged short-circuit; the resolver's JSDoc says so explicitly ("except to ADMIN/OWNER, who short-circuit first"). On substance, ADMIN/OWNER are allow-all for every *known* entity, so granting them an unknown one confers no privilege they don't already hold — there's no escalation path, and no call site can supply an attacker-controlled entity (all ~50 sites in both apps pass enum members or string literals; `as PermissionEntity` has zero hits).

So the proposed fix would change shipped behaviour — `roleHasPermission({roles:['ADMIN'], entity:<not in enum>})` goes `true` → `false` — inside a PR whose contract is *no behaviour change*, and would add two `Object.values()` allocations plus a 30-entity/15-action scan to every permission check, including every loader, to defend a case the type system already rules out.

Your instinct to pin it was fair, though: it read as an oversight, which is exactly the risk. `packages/permissions/src/resolver.test.ts` now covers both halves explicitly — ADMIN beating an unknown entity (with a `why:` comment recording that it matches pre-extraction behaviour) and the non-privileged safe-deny — so the ordering reads as intent to the next person.

**Review by DonKoko — APPROVED** [review]
